"""
@file directory_agent_state.py
@brief Defines the shared state structure used by the DirectoryAgent workflow.
"""

from typing import TypedDict, Deque
# from agent.structured_output.directory_output import DirectoryOutput

class DirectoryGraphState(TypedDict):
    """
    @brief Represents the state object shared between graph nodes in the DirectoryAgent workflow.
    @var directory_path The absolute path to the directory being analyzed.
    @var directories A deque containing directory paths discovered during traversal.
    @var directory_summary A summary of the current directory, generated by the DirectoryAgent.
    @var codebase_name The name of the codebase being analyzed.
    @var total_number_of_directories The total count of directories discovered during traversal.
    @var current_directory The path of the current directory being processed.
    """
    directory_path: str
    directories: Deque[str]
    # directory_summary: DirectoryOutput
    codebase_name: str
    total_number_of_directories: int
    current_directory: str