"""
@file build_database_JSON.py
@brief Core script for indexing a codebase into a ChromaDB vector store.
@details This script performs the ETL (Extract, Transform, Load) process for structured 
LLM-generated summaries. It reads JSON files from a specified directory, flattens the 
hierarchical data (files, classes, and methods), and upserts them as searchable 
embeddings into a persistent ChromaDB collection.
"""

import json
import sys
import chromadb
from pathlib import Path
from chromadb.utils.embedding_functions import SentenceTransformerEmbeddingFunction


def build_database(codebase_name: str) -> None:
    """
    @brief Assembles a local ChromaDB database from a directory of JSON files.
    
    @details
    This function:
    1. Locates the JSON summaries generated by the FileSummaryAgent.
    2. Initializes a persistent ChromaDB client and embedding function.
    3. Flattens the nested JSON structure into unique vector nodes for:
       - File-level summaries
       - Top-level functions
       - Classes and their internal methods
    4. Performs an upsert operation to the database to ensure no duplicate entries 
       exist within the specific collection.

    @param codebase_name str: The name of the codebase folder to index (e.g., "ConsoleTables").
    @return None
    """
    script_dir = Path(__file__).parent.resolve()
    # Path to where the agent saved the JSONs
    json_dir = (script_dir.parent / "agent" / "file_summary_agent_output" / codebase_name).resolve()
    db_dir = (script_dir.parent / "vectorStores").resolve()

    if not json_dir.exists() or not json_dir.is_dir():
        print(f"Error: The provided JSON directory '{json_dir}' does not exist or is not a directory.")
        sys.exit(1)
    
    # Init Chroma Client
    client = chromadb.PersistentClient(path=str(db_dir))
    embedding_fn = SentenceTransformerEmbeddingFunction(model_name="all-MiniLM-L6-v2")

    collection_name = f"{codebase_name}_summary_db"
    print(f"\n--- Building Collection: {collection_name} ---")
    collection = client.get_or_create_collection(name=collection_name, embedding_function=embedding_fn)

    ids = []
    documents = []
    metadatas = []

    for file_path in json_dir.glob("*.json"):
        with open(file_path, "r", encoding="utf-8") as f:
            data = json.load(f)
        
        src_path = data.get("path", "unknown")

        # 1. File Level Node
        f_id = f"file:{src_path}"
        if f_id not in ids:
            ids.append(f_id)
            documents.append(f"File Path: {src_path}\nGlobal Summary: {data.get('summary', '')}")
            metadatas.append({"type": "file", "path": src_path})

        # 2. Top-Level Functions
        for func in data.get("functions", []):
            name = func.get("name")
            func_id = f"func:{src_path}:{name}"
            if func_id not in ids:
                ids.append(func_id)
                documents.append(f"Function '{name}' in {src_path}. Description: {func.get('description')}")
                metadatas.append({"type": "function", "name": name, "path": src_path})

        # 3. Classes & Their Methods
        for cls in data.get("classes", []):
            class_name = cls.get("name")
            class_id = f"class:{src_path}:{class_name}"
            
            if class_id not in ids:
                ids.append(class_id)
                documents.append(f"Class '{class_name}' in {src_path}. Description: {cls.get('description')}")
                metadatas.append({"type": "class", "name": class_name, "path": src_path})

            for method in cls.get("methods", []):
                m_name = method.get("name")
                method_id = f"method:{src_path}:{class_name}:{m_name}"
                
                if method_id not in ids:
                    ids.append(method_id)
                    documents.append(
                        f"Method '{m_name}' belonging to class '{class_name}' in {src_path}. "
                        f"Description: {method.get('description')}"
                    )
                    metadatas.append({
                        "type": "method", 
                        "name": m_name, 
                        "parent": class_name, 
                        "path": src_path
                    })

    # Final batch upsert
    if ids:
        collection.upsert(ids=ids, documents=documents, metadatas=metadatas)
        print(f"Finished indexing {len(ids)} unique items for {codebase_name}")

if __name__ == "__main__":
    """
    @brief Script entry point for the summary database builder.
    @details Validates command line arguments and initiates the indexing process.
    """
    if len(sys.argv) != 2:
        print("Usage: python build_database_JSON.py <json_directory>")
        sys.exit(1)
    build_database(sys.argv[1])